language: generic 
sudo: required
services:
        - docker

before_install:
        - docker build -t tfilipek/docker-react -f Dockerfile.dev .

script:
        - docker run tfilipek/docker-react npm run test -- --coverage
